Update install_essentials

diff --git a/install_essentials b/install_essentials
--- a/install_essentials
+++ b/install_essentials
@@ -15,8 +15,8 @@ sudo apt install $install_string -y
 
 if [[ $install_docker == "true" ]]
 then
-    #curl -sSL https://get.docker.com | sh || error "Failed to install Docker."
-    #sudo usermod -aG docker $USER || error "Failed to add user to the Docker usergroup."
+    curl -sSL https://get.docker.com | sh || error "Failed to install Docker."
+    sudo usermod -aG docker $USER || error "Failed to add user to the Docker usergroup."
     echo "Remember to logoff/reboot for the changes to take effect."
 fi
 
